#!/usr/bin/env bash
#
# install_hook.sh — يركب git hook يشغل sync_upstream.py بعد كل commit
# يعمل auto-sync للمهارات المطورة محلياً للمستودع المركزي.
#
# Usage: bash scripts/install_hook.sh
#        أو: make install-hook

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK_FILE="$REPO_ROOT/.git/hooks/post-commit"
SYNC_SCRIPT="$REPO_ROOT/scripts/sync_upstream.py"

echo "🔧 Installing post-commit hook for auto-sync..."

# تحقق إننا في git repo
if [[ ! -d "$REPO_ROOT/.git" ]]; then
    echo "❌ Not a git repository: $REPO_ROOT"
    exit 1
fi

# تحقق إن sync_upstream.py موجود
if [[ ! -f "$SYNC_SCRIPT" ]]; then
    echo "❌ sync_upstream.py not found at $SYNC_SCRIPT"
    exit 1
fi

# إنشاء الـ hook
cat > "$HOOK_FILE" << 'EOF'
#!/usr/bin/env bash
#
# Auto-generated by install_hook.sh
# Runs sync_upstream.py after each commit to push community contributions.
#

# لا تشغل لو في rebase/merge/cherry-pick
if [[ -n "${GIT_DIR:-}" && -f "$GIT_DIR/REBASE_HEAD" ]]; then
    exit 0
fi
if [[ -n "${GIT_DIR:-}" && -f "$GIT_DIR/MERGE_HEAD" ]]; then
    exit 0
fi
if [[ -n "${GIT_DIR:-}" && -f "$GIT_DIR/CHERRY_PICK_HEAD" ]]; then
    exit 0
fi

# لا تشغل لو الـ commit message فيه [skip-sync]
COMMIT_MSG=$(git log -1 --pretty=%B)
if [[ "$COMMIT_MSG" == *"[skip-sync]"* ]]; then
    echo "⏭️  Skipping sync (commit has [skip-sync])"
    exit 0
fi

# شغل sync في الخلفية (لا يحول المستخدم)
echo "🔄 Auto-sync triggered..."
nohup "$REPO_ROOT/venv/bin/python" "$REPO_ROOT/scripts/sync_upstream.py" \
    >> "$REPO_ROOT/logs/sync_upstream.log" 2>&1 &

echo "✅ Sync started in background (PID: $!)"
echo "   Logs: $REPO_ROOT/logs/sync_upstream.log"
EOF

chmod +x "$HOOK_FILE"

# إنشاء مجلد اللوجز
mkdir -p "$REPO_ROOT/logs"

echo "✅ Hook installed at $HOOK_FILE"
echo ""
echo "📋 How it works:"
echo "   1. You commit changes (skills, rules, CLAUDE.md, etc.)"
echo "   2. Hook triggers sync_upstream.py in background"
echo "   3. Script collects changes, pushes branch, opens PR"
echo "   4. GitHub Actions validates + auto-merges if green"
echo ""
echo "🛑 To skip sync for a commit:"
echo "   git commit -m 'your message [skip-sync]'"
echo ""
echo "📝 Logs: $REPO_ROOT/logs/sync_upstream.log"