#!/usr/bin/env bash
#
# install_hook.sh — install a git hook that runs sync_upstream.py after each commit
# for auto-sync of locally-improved skills to the central repo.
#
# Usage: bash scripts/install_hook.sh
#        or: make install-hook

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK_FILE="$REPO_ROOT/.git/hooks/post-commit"
SYNC_SCRIPT="$REPO_ROOT/scripts/sync_upstream.py"

echo "🔧 Installing post-commit hook for auto-sync..."

# must be a git repo
if [[ ! -d "$REPO_ROOT/.git" ]]; then
    echo "❌ Not a git repository: $REPO_ROOT"
    exit 1
fi

# sync_upstream.py must exist
if [[ ! -f "$SYNC_SCRIPT" ]]; then
    echo "❌ sync_upstream.py not found at $SYNC_SCRIPT"
    exit 1
fi

# create the hook
cat > "$HOOK_FILE" << 'EOF'
#!/usr/bin/env bash
#
# Auto-generated by install_hook.sh
# Runs sync_upstream.py after each commit to push community contributions.
#

# don't run during rebase/merge/cherry-pick
if [[ -n "${GIT_DIR:-}" && -f "$GIT_DIR/REBASE_HEAD" ]]; then
    exit 0
fi
if [[ -n "${GIT_DIR:-}" && -f "$GIT_DIR/MERGE_HEAD" ]]; then
    exit 0
fi
if [[ -n "${GIT_DIR:-}" && -f "$GIT_DIR/CHERRY_PICK_HEAD" ]]; then
    exit 0
fi

# don't run when the commit message has [skip-sync]
COMMIT_MSG=$(git log -1 --pretty=%B)
if [[ "$COMMIT_MSG" == *"[skip-sync]"* ]]; then
    echo "Skipping sync (commit has [skip-sync])"
    exit 0
fi

# run sync in the background (never blocks the user)
echo "Auto-sync triggered..."
nohup "$REPO_ROOT/venv/bin/python" "$REPO_ROOT/scripts/sync_upstream.py" \
    >> "$REPO_ROOT/logs/sync_upstream.log" 2>&1 &

echo "Sync started in background (PID: $!)"
echo "   Logs: $REPO_ROOT/logs/sync_upstream.log"
EOF

chmod +x "$HOOK_FILE"

# create the logs dir
mkdir -p "$REPO_ROOT/logs"

echo "Hook installed at $HOOK_FILE"
echo ""
echo "How it works:"
echo "   1. You commit changes (skills, rules, CLAUDE.md, etc.)"
echo "   2. Hook triggers sync_upstream.py in background"
echo "   3. Script collects changes, pushes branch, opens PR"
echo "   4. GitHub Actions validates; a human maintainer reviews and merges"
echo ""
echo "To skip sync for a commit:"
echo "   git commit -m 'your message [skip-sync]'"
echo ""
echo "Logs: $REPO_ROOT/logs/sync_upstream.log"