#!/usr/bin/env python3
"""
sync_upstream.py — collect local changes and send them as a PR to the central repo.

Runs automatically after each self-improvement cycle
(skillopt-sleep + autonomous-model-self-evolver).
"""

import os
import sys
import subprocess
import json
import tempfile
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))
from setup_consent import check_consent  # consent gate — background never sends without consent
GITIGNORE_PATHS = [
    ".env", "*.env", ".env.*",
    "venv/", ".venv/", "env/",
    ".operator/",
    "memory/.sessions/",
    "*.db", "*.db-*",
    "__pycache__/", "*.pyc",
    ".pytest_cache/",
    ".mypy_cache/",
    "*.log",
    ".DS_Store",
]


def run(cmd: List[str], cwd: Path = None, capture: bool = True) -> subprocess.CompletedProcess:
    """Run a command with clean error handling."""
    try:
        return subprocess.run(
            cmd, cwd=cwd or REPO_ROOT,
            capture_output=capture, text=True, check=False
        )
    except Exception as e:
        print(f"❌ Command failed: {' '.join(cmd)} — {e}")
        return subprocess.CompletedProcess(cmd, 1, "", str(e))


def get_changed_files() -> List[str]:
    """Changed files since last sync (tracked + untracked skills/memory)."""
    # tracked changes
    res = run(["git", "status", "--porcelain"])
    tracked = [line[3:].strip() for line in res.stdout.splitlines() if line.strip()]

    # untracked skills/memory only
    res = run(["git", "ls-files", "--others", "--exclude-standard"])
    untracked = [f for f in res.stdout.splitlines()
                 if f.startswith((".opencode/skills/", "memory/", "CLAUDE.md", "scripts/"))]

    all_changes = list(set(tracked + untracked))
    # gitignore filter
    filtered = []
    for f in all_changes:
        if not any(f.startswith(ign.rstrip("/")) or f.endswith(ign.lstrip("*")) for ign in GITIGNORE_PATHS):
            filtered.append(f)
    return filtered


def has_meaningful_changes(files: List[str]) -> bool:
    """Any changes worth a PR? (not just whitespace)."""
    if not files:
        return False
    for f in files:
        if f.endswith((".md", ".json", ".py", ".yml", ".yaml")):
            return True
    return False


def create_pr_branch() -> str:
    """A unique branch name for the PR."""
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return f"community-contributions/{timestamp}"


def commit_and_push(branch: str, files: List[str]) -> bool:
    """Commit + push the branch."""
    # Add
    for f in files:
        run(["git", "add", f])

    # Commit message
    msg = f"chore: community sync {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
    msg += f"Auto-sync from local evolution cycle.\n\nFiles ({len(files)}):\n"
    for f in sorted(files):
        msg += f"  - {f}\n"
    msg += "\n🤖 Generated by sync_upstream.py"

    res = run(["git", "commit", "-m", msg])
    if res.returncode != 0:
        if "nothing to commit" in res.stdout:
            print("ℹ️  No changes to commit")
            return False
        print(f"❌ Commit failed: {res.stderr}")
        return False

    # Push
    res = run(["git", "push", "origin", branch, "-u"])
    if res.returncode != 0:
        print(f"❌ Push failed: {res.stderr}")
        return False

    print(f"✅ Pushed to origin/{branch}")
    return True


def create_pr(branch: str) -> Optional[str]:
    """Open a PR via the gh CLI."""
    title = f"🤖 Community sync: {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    body = f"""## Community Evolution Sync

Automated PR from local skill evolution cycle.

**Source**: Local development session
**Timestamp**: {datetime.now().isoformat()}
**Branch**: `{branch}`

### Changes Included
- Skills updated/new from `skillopt-sleep` consolidation
- `rules.json` from `autonomous-model-self-evolver` 
- `CLAUDE.md` / `memory/conversation-memory.md` updates
- Any new skill additions

### Testing
- [ ] `validate_workflow` passes
- [ ] `skillopt_sleep.experiments.run_experiment` passes
- [ ] No breaking changes to existing skills

---
*Auto-generated by `scripts/sync_upstream.py`*
"""

    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(body)
        body_file = f.name

    try:
        res = run(["gh", "pr", "create", "--title", title, "--body-file", body_file, "--base", "main", "--head", branch])
        os.unlink(body_file)
        if res.returncode == 0:
            pr_url = res.stdout.strip()
            print(f"✅ PR created: {pr_url}")
            return pr_url
        else:
            print(f"❌ PR creation failed: {res.stderr}")
            return None
    except Exception as e:
        print(f"❌ PR creation error: {e}")
        return None


def main():
    print("🔄 Starting upstream sync...")

    # must be a git repo
    if not (REPO_ROOT / ".git").exists():
        print("❌ Not a git repository")
        sys.exit(1)

    # consent gate (background mode = non-interactive: safe default is no send)
    if not check_consent(interactive=False):
        print("Sharing is off (no recorded consent) — skipping sync.")
        sys.exit(0)

    # must have a remote
    res = run(["git", "remote", "get-url", "origin"])
    if res.returncode != 0:
        print("❌ No 'origin' remote configured")
        sys.exit(1)

    # collect changes
    changed = get_changed_files()
    print(f"📝 Found {len(changed)} changed files:")
    for f in sorted(changed):
        print(f"   - {f}")

    if not has_meaningful_changes(changed):
        print("ℹ️  No meaningful changes to sync")
        sys.exit(0)

    # create branch + push
    branch = create_pr_branch()
    print(f"Creating branch: {branch}")

    # Switch to new branch
    run(["git", "checkout", "-b", branch])

    if not commit_and_push(branch, changed):
        print("❌ Sync failed at commit/push stage")
        sys.exit(1)

    # open the PR
    pr_url = create_pr(branch)
    if pr_url:
        print(f"🎉 Sync complete! PR: {pr_url}")
    else:
        print("⚠️  Push succeeded but PR creation failed. Check GitHub manually.")
        sys.exit(1)


if __name__ == "__main__":
    main()